spring.datasource.url=${DATASOURCE_URL:jdbc:mysql://localhost:3306/student_db}
spring.datasource.username=${DATASOURCE_USERNAME:root}
spring.datasource.password=${DATASOURCE_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8081}
spring.web.cors.allowed-origins=*
